// 客服电话
export const SERVICE_PHONE = '4000128532';
export const SERVICE_PHONE_FORMATTED = SERVICE_PHONE.replace(/^(\d{3})(\d{4})(\d*)$/, '$1-$2-$3');
// 场次
export const SCHEDULE_NAME = ['中午场', '下午场', '晚场'];
export const SCHEDULE_TIME = ['11:30～13:30', '15:30～17:30', '18:30～20:30'];

// 图片占位符
export const IMAGE_PLACEHOLDER = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';

// 主题详情获取状态
export const THEME_DETAIL_FETCHING = 'THEME_DETAIL_FETCHING';
export const THEME_DETAIL_FETCH_SUCCESS = 'THEME_DETAIL_FETCH_SUCCESS';
export const THEME_DETAIL_FETCH_FAIL = 'THEME_DETAIL_FETCH_FAIL';

// 主题列表获取状态
export const THEME_LIST_FETCHING = 'THEME_LIST_FETCHING';
export const THEME_LIST_FETCH_SUCCESS = 'THEME_LIST_FETCH_SUCCESS';
export const THEME_LIST_FETCH_FAIL = 'THEME_LIST_FETCH_FAIL';

// 主题分类列表获取状态
export const THEME_CATEGORY_FETCHING = 'THEME_CATEGORY_FETCHING';
export const THEME_CATEGORY_FETCH_FAIL = 'THEME_CATEGORY_FETCH_FAIL';
export const THEME_CATEGORY_FETCH_SUCCESS = 'THEME_CATEGORY_FETCH_SUCCESS';

// 案例数据获取状态
export const CASE_LIST_FETCH_SUCCESS = 'CASE_LIST_FETCH_SUCCESS';
export const CASE_DETAIL_FETCH_SUCCESS = 'CASE_DETAIL_FETCH_SUCCESS';
export const CASE_DETAIL_FETCH_FAIL = 'CASE_DETAIL_FETCH_FAIL';

// 套餐列表获取状态
export const COMBO_LIST_FETCHING = 'COMBO_LIST_FETCHING';
export const COMBO_LIST_FETCH_SUCCESS = 'COMBO_LIST_FETCH_SUCCESS';
export const COMBO_LIST_FETCH_FAIL = 'COMBO_LIST_FETCH_FAIL';

// 套餐详情获取状态
export const COMBO_DETAIL_FETCHING = 'COMBO_DETAIL_FETCHING';
export const COMBO_DETAIL_FETCH_SUCCESS = 'COMBO_DETAIL_FETCH_SUCCESS';
export const COMBO_DETAIL_FETCH_FAIL = 'COMBO_DETAIL_FETCH_FAIL';

// 当前用户获取状态
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL';
export const USER_FETCHING = 'USER_FETCHING';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';

// 邀请函列表获取状态
export const INVITATION_LIST_FETCHING = 'INVITATION_LIST_FETCHING';
export const INVITATION_LIST_FETCH_SUCCESS = 'INVITATION_LIST_FETCH_SUCCESS';
export const INVITATION_LIST_FETCH_FAIL = 'INVITATION_LIST_FETCH_FAIL';

// 邀请函详情获取状态
export const INVITATION_DETAIL_FETCHING = 'INVITATION_DETAIL_FETCHING';
export const INVITATION_DETAIL_FETCH_SUCCESS = 'INVITATION_DETAIL_FETCH_SUCCESS';
export const INVITATION_DETAIL_FETCH_FAIL = 'INVITATION_DETAIL_FETCH_FAIL';

// 相冊列表获取状态
export const PHOTO_LIST_FETCHING = 'PHOTO_LIST_FETCHING';
export const PHOTO_LIST_FETCH_SUCCESS = 'PHOTO_LIST_FETCH_SUCCESS';
export const PHOTO_lIST_FETCH_FAIL = 'PHOTO_lIST_FETCH_FAIL';

// 相册详情获取状态
export const PHOTO_DETAIL_FETCHING = 'PHOTO_DETAIL_FETCHING';
export const PHOTO_DETAIL_FETCH_SUCCESS = 'PHOTO_DETAIL_FETCH_SUCCESS';
export const PHOTO_DETAIL_FETCH_FAIL = 'PHOTO_DETAIL_FETCH_FAIL';

// 相册分享获取状态
export const SHARE_PHOTO_FETCHING = 'SHARE_PHOTO_FETCHING';
export const SHARE_PHOTO_FETCH_SUCCESS = 'SHARE_PHOTO_FETCH_SUCCESS';
export const SHARE_PHOTO_FETCH_FAIL = 'SHARE_PHOTO_FETCH_FAIL';

export const ALBUM_SHARE_FETCHING = 'ALBUM_SHARE_FETCHING';
export const ALBUM_SHARE_FETCH_SUCCESS = 'ALBUM_SHARE_FETCH_SUCCESS';
export const ALBUM_SHARE_FETCH_FAIL = 'ALBUM_SHARE_FETCH_FAIL';

// 我的二维码状态
export const USER_QRCODE_FETCHING = 'USER_QRCODE_FETCHING';
export const USER_QRCODE_FETCH_SUCCESS = 'USER_QRCODE_FETCH_SUCCESS';
export const USER_QRCODE_FETCH_FAIL = 'USER_QRCODE_FETCH_FAIL';

// 更新订单数据
export const UPDATE_ORDER_FORM = 'UPDATE_ORDER_FORM';
export const CLEAR_ORDER_FORM = 'CLEAR_ORDER_FORM';

// 订单信息获取状态
export const ORDER_DETAIL_FETCHING = 'ORDER_DETAIL_FETCHING';
export const ORDER_DETAIL_FETCH_SUCCESS = 'ORDER_DETAIL_FETCH_SUCCESS';
export const ORDER_DETAIL_FETCH_FAIL = 'ORDER_DETAIL_FETCH_FAIL';

// 订单列表获取状态
export const ORDER_LIST_FETCHING = 'ORDER_LIST_FETCHING';
export const ORDER_LIST_FETCH_SUCCESS = 'ORDER_LIST_FETCH_SUCCESS';
export const ORDER_LIST_FETCH_FAIL = 'ORDER_LIST_FETCH_FAIL';

// 订单状态
export const ORDER_STATUS_UNPAID = 100; // 等待付款
export const ORDER_STATUS_WAITING_FOR_CONFIRM = 200; // 方案确认中
export const ORDER_STATUS_WAITING_FOR_UPDATE = 210; // 修改待确认
export const ORDER_STATUS_CONFIRMED = 230; // 方案已确认
export const ORDER_STATUS_PREPARING = 250; // 筹备中
export const ORDER_STATUS_PREPARED = 300; // 筹备完成
export const ORDER_STATUS_COMPLETE = 400; // 举办完成
export const ORDER_STATUS_CANCELED = 500;// 取消订单
export const ORDER_STATUS_PLACE_LOCKED = 600; // 场地被锁定
export const ORDER_STATUS_TICKET_LOCKED = 700; // 优惠券锁定

// 订单状态文案
export const ORDER_STATUS_TEXT = {
    100: '等待付款',
    200: '方案确认中',
    210: '方案调整待支付',
    230: '方案已确认',
    250: '筹备中',
    300: '筹备完成',
    400: '举办完成',
    500: '取消订单',
    600: '方案确认中',
    700: '方案确认中'
};

// 相册上传状态
export const ALBUM_STATUS_NOT_UPLOADED = 0;
export const ALBUM_STATUS_UPLOADED = 200;
export const ALBUM_STATUS_UNAVAILABLE = 500;

// 增值商品列表获取状态
export const COMMODITY_LIST_FETCHING = 'COMMODITY_LIST_FETCHING';
export const COMMODITY_LIST_FETCH_SUCCESS = 'COMMODITY_LIST_FETCH_SUCCESS';
export const COMMODITY_LIST_FETCH_FAIL = 'COMMODITY_LIST_FETCH_FAIL';

// 额外成人价格信息获取状态
export const ADULT_COMMODITY_FETCHING = 'ADULT_COMMODITY_FETCHING';
export const ADULT_COMMODITY_FETCH_SUCCESS = 'ADULT_COMMODITY_FETCH_SUCCESS';
export const ADULT_COMMODITY_FETCH_FAIL = 'ADULT_COMMODITY_FETCH_FAIL';

// 额外小孩价格信息获取状态
export const CHILD_COMMODITY_FETCHING = 'CHILD_COMMODITY_FETCHING';
export const CHILD_COMMODITY_FETCH_SUCCESS = 'CHILD_COMMODITY_FETCH_SUCCESS';
export const CHILD_COMMODITY_FETCH_FAIL = 'CHILD_COMMODITY_FETCH_FAIL';

// 场地列表获取状态
export const PLACE_LIST_FETCHING = 'PLACE_LIST_FETCHING';
export const PLACE_LIST_FETCH_SUCCESS = 'PLACE_LIST_FETCH_SUCCESS';
export const PLACE_LIST_FETCH_FAIL = 'PLACE_LIST_FETCH_FAIL';

// 场地详情获取状态
export const PLACE_DETAIL_FETCHING = 'PLACE_DETAIL_FETCHING';
export const PLACE_DETAIL_FETCH_SUCCESS = 'PLACE_DETAIL_FETCH_SUCCESS';
export const PLACE_DETAIL_FETCH_FAIL = 'PLACE_DETAIL_FETCH_FAIL';

// 优惠券列表获取状态
export const COUPON_LIST_FETCHING = 'COUPON_LIST_FETCHING';
export const COUPON_LIST_FETCH_SUCCESS = 'COUPON_LIST_FETCH_SUCCESS';
export const COUPON_LIST_FETCH_FAIL = 'COUPON_LIST_FETCH_FAIL';

// 城市状态
export const CITY_UPDATING = 'CITY_UPDATING';
export const CITY_UPDATE = 'CITY_UPDATE';

// banner 获取状态
export const BANNER_FETCHING = 'BANNER_FETCHING';
export const BANNER_FETCH_SUCCESS = 'BANNER_FETCH_SUCCESS';
export const BANNER_FETCH_FAIL = 'BANNER_FETCH_FAIL';
